apiVersion: apps/v1
kind: Deployment
metadata:
  name: precedents
spec:
  template:
    metadata:
      labels:
        precedents-nats-client: null
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - $patch: delete
          name: MONGO_URI
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: precedents-secrets
        - name: MONGO_URI
          value: $(MONGODB_URI)
        - $patch: delete
          name: KEY_IDENTIFIER
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: precedents-secrets
        - name: KEY_IDENTIFIER
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - $patch: delete
          name: SELF_SIGNING_PRIVATE_KEY
        - name: TOKEN_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKey
              name: precedents-secrets
        - name: SELF_SIGNING_PRIVATE_KEY
          value: $(TOKEN_AUTH_PRIVATE_KEY)
        - $patch: delete
          name: AUTH_JWKS_URI
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: precedents-configs
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal
        - $patch: delete
          name: EDGE_AUTH_URI          
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: precedents-configs
        - name: EDGE_AUTH_URI
          value: $(TOKEN_AUTH_URI)
        - $patch: delete
          name: NATS_URL
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: precedents-configs
        - name: NATS_URL
          value: $(NATS_URI)
        - $patch: delete
          name: NATS_CLUSTER_ID
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: precedents-configs
        - name: NATS_CLUSTER_ID
          value: $(NATS_STREAMING_CLUSTER_ID)
        - $patch: delete
          name: ENGINEADDRESS
        # - name: QIX_SESSIONS_URI
        #   valueFrom:
        #     configMapKeyRef:
        #       key: qixSessionsUri
        #       name: precedents-configs
        - name: ENGINEADDRESS
          value: http://$(PREFIX)-qix-sessions
          # value: $(QIX_SESSIONS_URI)
        - $patch: delete
          name: FEATURE_FLAG_URL
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: precedents-configs
        - name: FEATURE_FLAG_URL
          value: $(FEATURE_FLAGS_URI)
        - $patch: delete
          name: SPACES_URI
        - name: SPACES_URI
          valueFrom:
            configMapKeyRef:
              key: spacesUri
              name: precedents-configs