apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: precedents
enabled: true
patches:
patches:
  - path: deploymentJSON.yaml
    target:
      kind: Deployment
      name: insights
  - path: cronJobJSON.yaml
    target:
      kind: CronJob
  - path: deployment.yaml
    target:
      kind: Deployment
  - path: cronJob.yaml
    target:
      kind: CronJob
