apiVersion: apps/v1
kind: Deployment
metadata:
  name: groups
spec:
  template:
    spec:
      volumes:
      - name: groups-secret
        secret:
          secretName: groups-secrets
          items:
            - key: tokenAuthPrivateKey
              path: jwtPrivateKey
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: groups-secrets
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)
        - $patch: delete
          name: FEATURE_FLAGS_URI
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: groups-configs
        - $patch: delete
          name: FEATURE_FLAGS_RESOURCE
        - name: FEATURE_FLAGS_RESOURCE
          value: $(FEATURE_FLAGS_URI)
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: groups-configs
        - $patch: delete
          name: JWKS_ENDPOINT
        - name: JWKS_ENDPOINT
          value: $(KEYS_URI)/keys/qlik.api.internal
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: groups-configs
        - $patch: delete
          name: INTERNAL_TOKENS_RESOURCE
        - name: INTERNAL_TOKENS_RESOURCE
          value: $(TOKEN_AUTH_URI)/v1
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: groups-secrets
        - $patch: delete
          name: KEY_ID
        - name: KEY_ID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID )
        - name: USERS_URI
          valueFrom:
            configMapKeyRef:
              key: usersUri
              name: groups-configs
        - name: USERS_RESOURCE
          value: $(USERS_URI)
