apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-keys
spec:
  template:
    spec:
      containers:
        - name: main
          env:
            - $patch: delete
              name: KEYS_URI
            - name: KEYS_URI
              value: $(KEYS_URI_TEMP)/keys/qlik.api.internal
