apiVersion: builtin
kind: PatchTransformer
metadata:
  name: notImportantHere
target:
  name: dcaas-configs
  kind: SuperConfigMap
patch: '[{"op": "remove", "path": "/data/featureFlagsUri"}, {"op": "remove", "path": "/data/keysUri"}, {"op": "remove", "path": "/data/spacesUri"}, {"op": "remove", "path": "/data/qixDataConnectionUri"}]'
