apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: edge-auth-component-secrets
enabled: true
patches:
- target:
    kind: SuperSecret
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: edge-auth-secrets
    stringData:
      tokenAuthPrivateKeyId: ""
      tokenAuthPrivateKey: |
        ((- "\n"))(( (ds "data").private_key | indent 8 ))
      loginStateKey: (( (ds "data").loginStateKey ))
    data:
      cookiesKeys: WyJVaUw2WWVQRWNVTWsyTXFpR2sxQnVHc3FNV2ZvSHorYjFTdVgxM2xLdXZVPSJd

- target:
    kind: Secret
    name: edge-auth-secrets
  patch: |-
    - op: add
      path: /stringData
      value:
        mongoDbUri: mongodb://$(PREFIX)-mongodb:27017/edge-auth
