apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-defaultUserPassword
  labels:
    key: defaultUserPassword
target:
  kind: SuperSecret
  name: keycloak-realm
path: stringData/realm.json
search: \$\(DEFAULT_USER_PASSWORD\)
replaceWithObjRef:
  objref:
    kind: SuperSecret
    name: keycloak-secrets
  fieldref:
    fieldpath: stringData.defaultUserPassword
