apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
vars:
  - name: NAMESPACE
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: configs
    fieldref:
      fieldpath: metadata.namespace
  - name: PREFIX
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: configs
    fieldref:
      fieldpath: metadata.labels.release
  - name: INGRESS_CLASS
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: configs
    fieldref:
      fieldpath: data.ingressClass
  - name: IMAGE_REGISTRY
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: configs
    fieldref:
      fieldpath: data.imageRegistry
  - name: STORAGE_CLASS_NAME
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: configs
    fieldref:
      fieldpath: data.storageClassName
configurations:
  - varreference.yaml
resources:
  - resources
