varReference:
- path: metadata/annotations/nginx.ingress.kubernetes.io\/auth-url
  kind: Ingress
- path: metadata/annotations/kubernetes.io\/ingress.class
  kind: Ingress
- path: metadata/annotations/nginx.ingress.kubernetes.io\/server-snippet
  kind: Ingress
- path: metadata/namespace
  kind: Ingress
- path: metadata/labels/
  kind: Deployment
- path: spec/template/metadata/labels/qlik.com\/engine-deployment-name
  kind: Deployment
- path: metadata/name
  kind: Deployment
- path: metadata/name
  kind: CronJob
- path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
  kind: Deployment
- path: spec/template/spec/containers/env/valueFrom/configMapKeyRef/name
  kind: Deployment
- path: spec/template/spec/initContainers/env/valueFrom/secretKeyRef/name
  kind: Deployment
- path: spec/template/spec/initContainers/env/valueFrom/configMapKeyRef/name
  kind: Deployment
- path: spec/template/spec/volumes/secret/secretName
  kind: Deployment
- path: spec/template/spec/containers/args
  kind: Deployment
- path: spec/template/spec/serviceAccountName
  kind: Deployment
- path: spec/template/spec/volumes/configMap/name
  kind: Deployment
- path: spec/template/spec/volumes/persistentVolumeClaim/claimName
  kind: Deployment
- path: spec/template/spec/containers/image
  kind: Deployment
- path: spec/jobTemplate/spec/template/spec/containers/image
  kind: CronJob
- path: data/policyDecisionsUri
  kind: ConfigMap
- path: spec/serviceName
  kind: StatefulSet
- path: metadata/name
  kind: StatefulSet
- path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
  kind: StatefulSet
- path: spec/jobTemplate/spec/template/spec/containers/env/valueFrom/secretKeyRef/name
  kind: CronJob
- path: spec/jobTemplate/spec/template/spec/containers/env/valueFrom/configMapKeyRef/name
  kind: CronJob
- path: spec/template/spec/containers/env/valueFrom/configMapKeyRef/name
  kind: StatefulSet
- path: spec/template/spec/serviceAccountName
  kind: StatefulSet
- path: spec/template/spec/containers/args
  kind: StatefulSet
- path: spec/template/spec/volumes/configMap/name
  kind: StatefulSet
- path: spec/template/spec/containers/image
  kind: StatefulSet
- path: metadata/name
  kind: Service
- path: metadata/name
  kind: Ingress
- path: spec/rules/http/paths/backend/serviceName
  kind: Ingress
- path: metadata/name
  kind: Secret
- path: stringData/redis-addr
  kind: Secret
- path: data/mongodbUri
  kind: Secret
- path: stringData/mongodbUri
  kind: Secret
- path: metadata/name
  kind: ConfigMap
- path: data/natsUri
  kind: ConfigMap
- path: data/featureFlagsUri
  kind: ConfigMap
- path: data/keysUri
  kind: ConfigMap
- path: data/natsStreamingClusterId
  kind: ConfigMap
- path: data/edgeAuthUri
  kind: ConfigMap
- path: data/ingressAuthUrl
  kind: ConfigMap
- path: data/imageRegistry
  kind: ConfigMap
- path: data/groupsUri
  kind: ConfigMap
- path: data/identityProvidersUri
  kind: ConfigMap
- path: data/identityProvidersExtUri
  kind: ConfigMap
- path: data/tenantsUri
  kind: ConfigMap
- path: data/usersUri
  kind: ConfigMap
- path: metadata/name
  kind: ServiceAccount
- path: metadata/name
  kind: Role
- path: metadata/name
  kind: RoleBinding
- path: roleRef/name
  kind: RoleBinding
- path: subjects/name
  kind: RoleBinding
- path: metadata/name
  kind: NetworkPolicy
- kind: ConfigMap
  path: data/connectorServices
- kind: ConfigMap
  path: data/dcaasDataConnectionUri
- kind: ConfigMap
  path: data/qixDataConnectionUri
- kind: ConfigMap
  path: data/redisUri
- kind: ConfigMap
  path: data/redisUriWithPort
- kind: ConfigMap
  path: data/redisHost
- kind: ConfigMap
  path: data/spacesUri
- kind: ConfigMap
  path: data/qixSessionsUri
- kind: ConfigMap
  path: data/dataFilesUri
- kind: ConfigMap
  path: data/qixDataFilesUri
- kind: ConfigMap
  path: data/precedentsUri
- kind: ConfigMap
  path: data/engineUri
- path: spec/podSpec/containers/env/valueFrom/secretKeyRef/name
  kind: Engine
- path: spec/podSpec/containers/env/valueFrom/configMapKeyRef/name
  kind: Engine
- path: spec/podSpec/volumes/secret/secretName
  kind: Engine
- path: spec/podSpec/volumes/configMap/name
  kind: Engine
- path: metadata/name
  kind: Engine
- path: metadata/name
  kind: PersistentVolumeClaim
- path: spec/podSpec/volumes/persistentVolumeClaim/claimName
  kind: Engine
- path: spec/podSpec/containers/image
  kind: Engine
- kind: ConfigMap
  path: data/corsUri
- kind: ConfigMap
  path: data/encryptionUri
- kind: ConfigMap
  path: data/licensesUri
- kind: ConfigMap
  path: data/quotasUri
- kind: ConfigMap
  path: data/temporaryContentsUri
- kind: ConfigMap
  path: data/gnatsd.conf
- kind: ConfigMap
  path: data/geoOperationsUri
- kind: ConfigMap
  path: data/dcaasUri
- kind: ConfigMap
  path: data/dataPrepUri
- kind: ConfigMap
  path: data/nlParserUri
- kind: Role
  path: rules/resourceNames
- kind: RoleBinding
  path: subjects/namespace
- kind: PersistentVolumeClaim
  path: spec/storageClassName
- kind: ConfigMap
  path: data/qixDataReloadUri
- kind: ConfigMap
  path: data/reloadTasksUri
- kind: ConfigMap
  path: data/chronosUri
- kind: ConfigMap
  path: data/collectionsUri
- kind: ConfigMap
  path: data/reportingUri
- kind: ConfigMap
  path: data/keysUriTemp
- kind: ConfigMap
  path: data/edgeAuthUriTemp
- kind: ConfigMap
  path: data/licensesUriTemp
- path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
  kind: Job
- path: spec/template/spec/containers/env/valueFrom/configMapKeyRef/name
  kind: Job
- path: spec/template/spec/volumes/persistentVolumeClaim/claimName
  kind: Job
- path: spec/jobTemplate/spec/template/spec/volumes/secret/secretName
  kind: CronJob
- path: metadata/name
  kind: Job
- path: metadata/name
  kind: PersistentVolumeClaim
- path: metadata/name
  kind: HorizontalPodAutoscaler
- path: spec/scaleTargetRef/name
  kind: HorizontalPodAutoscaler
- path: data/parse_sentinels.awk
  kind: ConfigMap
- path: data/sentinel.conf
  kind: ConfigMap
- path: data/apiKeysUri
  kind: ConfigMap
- path: data/insightsUri
  kind: ConfigMap
- path: data/subscriptionsUri
  kind: ConfigMap
- path: data/dataConnectionsUri
  kind: ConfigMap
