apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
vars:
  - name: INGRESS_CLASS 
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: qix-data-reload-configs
    fieldref:
      fieldpath: data.ingressClass
  - name: NAMESPACE
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: qix-data-reload-configs 
    fieldref:
      fieldpath: metadata.namespace
  - name: PREFIX 
    objref:
      apiVersion: v1
      kind: ConfigMap 
      name: qix-data-reload-configs 
    fieldref:
      fieldpath: metadata.labels.release
  - name: INGRESS_AUTH_URL
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: qix-data-reload-configs
    fieldref:
      fieldpath: data.ingressAuthUrl
  - name: IMAGE_REGISTRY
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: qix-data-reload-configs
    fieldref:
      fieldpath: data.imageRegistry
configurations:
  - ../../varreference.yaml
resources:
  - ../../resources/qix-data-reload
