apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: temporary-contents
resources:
- ../../../../configs
transformers:
- ../../configs
patches:
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: temporary-contents-configs