apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: dcaas-web
resources:
- ../../../../secrets
transformers:
- ../../secrets
patches:
- target:
    kind: SuperSecret
  patch: |-
    - op: replace
      path: /metadata/name
      value: dcaas-web-secrets