apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-connections
spec:
  template:
    spec:
      containers:
      - name: main
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongodbUri
              name: data-connections-secrets
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)


        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: data-connections-configs
        - $patch: delete
          name: JWKS_URI
        - name: JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: data-connections-configs
        - $patch: delete
          name: NATS_CLUSTER_ID
        - name: NATS_CLUSTER_ID
          value: $(NATS_STREAMING_CLUSTER_ID)
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: data-connections-configs
        - $patch: delete
          name: NATS_ADDR
        - name: NATS_ADDR
          value: $(NATS_URI)
        - name: TOKEN_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKey
              name: data-connections-secrets
        - $patch: delete
          name: PRIVATE_KEY
        - name: PRIVATE_KEY
          value: $(TOKEN_AUTH_PRIVATE_KEY)
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: data-connections-secrets
        - $patch: delete
          name: KEY_ID
        - name: KEY_ID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: data-connections-configs
        - $patch: delete
          name: AUTH_URI
        - name: AUTH_URI
          value: $(TOKEN_AUTH_URI)
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: data-connections-configs
        - $patch: delete
          name: FEATURE_FLAG_ADDR
        - name: FEATURE_FLAG_ADDR
          value: $(FEATURE_FLAGS_URI)


        - name: QIX_DATA_FILES_URI
          valueFrom:
            configMapKeyRef:
              key: qixDataFilesUri
              name: data-connections-configs
        - $patch: delete
          name: DATAFILES_URI
        - name: DATAFILES_URI
          value: $(QIX_DATA_FILES_URI)
        - name: SPACES_URI
          valueFrom:
            configMapKeyRef:
              key: spacesUri
              name: data-connections-configs
        - $patch: delete
          name: SPACE_URI
        - name: SPACE_URI
          value: $(SPACES_URI)
        - name: ENCRYPTION_URI
          valueFrom:
            configMapKeyRef:
              key: encryptionUri
              name: data-connections-configs
        - $patch: delete
          name: E2S_ADDR
        - name: E2S_ADDR
          value: $(ENCRYPTION_URI)
