apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: qliksense-component-secrets
enabled: true
patches:
- target:
    kind: SuperSecret
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: all-secrets
    stringData:
      mongodbUri: "mongodb://qliksense-mongodb:27017/qliksense?ssl=false"
      redisPassword: "NGkUp0VDJtc3xiyC"
      caCertificates: |-
        -----BEGIN CERTIFICATE-----
        MIIE7jCCAtYCCQCuMixnfSSR3zANBgkqhkiG9w0BAQsFADA5MQswCQYDVQQGEwJD
        QTELMAkGA1UECAwCT04xCzAJBgNVBAcMAk9UMRAwDgYDVQQDDAdleGFtcGxlMB4X
        DTE5MDMwNjE0NDkzOFoXDTIxMTIyNDE0NDkzOFowOTELMAkGA1UEBhMCQ0ExCzAJ
        BgNVBAgMAk9OMQswCQYDVQQHDAJPVDEQMA4GA1UEAwwHZXhhbXBsZTCCAiIwDQYJ
        KoZIhvcNAQEBBQADggIPADCCAgoCggIBAMVaX4gDNkJflE1xP7ZXAfAFZSGVLaj6
        U809NqiwmrQtj491qOnT6WJK7m389kyI78cd1XF35TJcuNAeFEDF8bT9qn+y4nQ3
        qRd70wAyX4rG3aEWZhdWZ/9NdWmNviLndpyVo37I++ZKcji58EODWdDZZeUH0ekT
        RVuBeTyRrd53gEa7rWYVln320QFAfFJZk+2R/PY3yZTXRNGcaTZnQND3NN2COJ3n
        uVM9tUQfA4jH37+jBlZv1wlxMFk7lBmYEkbiHgcAnExzEn5KTJ9Yxt80J83w7x8r
        XBY14FiyiNH4SutE9UitBYoIAIAQyMPeKichpYXbZSGrA+t47xIj1kniBK9i/RFb
        MYBBwQk/zTX+pp2vJUAfd9eUkpDs23BwE10u/YBYZot5AaT8/CaowmdPXgmN+soU
        vKshbLfuEpmVoFi50Yedxp8rTKuhN8QFoP79Fo6aKQFghqT+feLi8MYbS9QGd8Wb
        pzF9CBFod8qiKsNW+G0a/oJA2wRYSbz6Vu1gRfjV4VNXix1MxEFuGxF8Uo1wv7Sq
        evA3W/SNUxJ98X46L+fJs10owKYxy5EztV1Kn84WaeENe9e+xiATuWL1IbHni/fV
        Ff+QJnc7jzgT41VUUyPYvMguTGZST8CmvEfJN9orYTtfu/6lOgDpIkQQ3J2Ar5zf
        iPctWShtNrrXAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAG6utIYY3C6SN4SPZB98
        5Tza0Shm4Y48IKs0cZNXwm5gL3WgJl5dYN3xO6+aga4CIWfXpxOm9GPiylDjA3N6
        wLJz+CATF17PhvaeqQfCaC+xUCuagqqgNC3+ONsdLs2J6gyg8/uIc5eQ+yj7O9rv
        Rh3/MUd0FtjL2GubU8pj1PpyQH4hTpJ0+1FBXbsl44hso53P4pf78Ihk/KEIWKBh
        ASH5ksorVFTNJ5+AN7WEjNTMbQUTMVOnApNLcrSbjgAeRP4UBd1hc1gfT7fkiiFe
        w8LBMtwkMAUrCXsPgILHkHOBq2b5Lwl9aVYVlnjhOskWOgFIiL7rm0Gg7ANyAq38
        61XOopGZOpMvR863m6n3wa37C67+KshRxUGnozjrBMSqAC0e+6yBQOWKN2xpjtM3
        Mx1mh6mHWp9mVIYTnPS4iPvf6J6nGer3megbMFgM68xzAMkv7t1rJHYvvVNoYIWy
        WZSxGt6hq0V3YiUIMEvH+EEYlJy2Acgg7eqtO8ykvzSJ0QEi00eUGZd1ZVb4HAKp
        2YU1CuuRPUuJJBZktziepww1P5XKeG/tn/tzD28lJhdqxRjYPBnyAF/QkGfDNwcR
        Awg054QnLh3jRWGnswZbNsYeC7K29QEnDneCVEtIT4Yn9LHkWX44IMG9pK7uoXJZ
        ZhcctBf1xVjSS6TW2UCbP7+O
        -----END CERTIFICATE-----
