apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- selectivepatch.yaml
#- ../../../../../.operator/keys/secrets/elastic-infra
- ../../../../../.operator/secrets
- ../../../../../configuration/secrets
