apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: encryption
    chart: encryption-2.5.4
    heritage: Helm
    release: encryption
  name: encryption
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encryption
      release: encryption
  template:
    metadata:
      labels:
        app: encryption
        release: encryption
    spec:
      containers:
      - env:
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/v1/keys/qlik.api.internal
        - name: AUTH_JWT_AUD
          value: qlik.api.internal/encryption
        - name: ENABLE_ADMIN_ENDPOINT
          value: "false"
        - name: AUTH_ENABLED
          value: "true"
        - name: LOG_LEVEL
          value: info
        - name: BACKEND_TYPE
          value: loopback
        image: qliktech-docker.jfrog.io/encryption:3.2.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        name: main
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        resources: null
      imagePullSecrets:
      - name: artifactory-docker-secret
      serviceAccountName: encryption
---
