apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: resource-library
resources:
  - ../../../transformers
transformers:
- ../../../../../.operator/transformers
- ../../../../../configuration/transformers
#Disable all transformers except these
patches:
- target:
    labelSelector: >-
      key notin ( 
        ingressClass,
        ingressAuthUrl,
        natsUri,
        natsStreamingClusterId,
        keysUri,
        tokenAuthUri,
        mongoDbUri,
        engineUri,
        qixSessionsUri,
        reloadServiceUri,
        usersUri,
        collectionsUri,
        featureFlagsUri,
        encryptionUri,
        tokenAuthPrivateKey,
        tokenAuthPrivateKeyId
      )
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: true
