apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - searchReplacePrefix.yaml
transformers:
  - ../../../../../../.operator/transformers
  - ../../../../../../configuration/transformers