apiVersion: apps/v1
kind: Deployment
metadata:
  name: odag
spec:
  template:
    metadata:
      labels:
        odag-nats-client: null
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: odag-secrets
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: odag-secrets
        - $patch: delete
          name: KEY_IDENTIFIER
        - name: KEY_IDENTIFIER
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - name: TOKEN_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKey
              name: odag-secrets
        - $patch: delete
          name: SELF_SIGNING_PRIVATE_KEY
        - name: SELF_SIGNING_PRIVATE_KEY
          value: $(TOKEN_AUTH_PRIVATE_KEY)
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: odag-configs
        - $patch: delete
          name: AUTH_JWKS_URI
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: qix-data-connection-configs
        - name: EDGE_AUTH_URL
          value: $(TOKEN_AUTH_URI)
        - $patch: delete
          name: ENGINE_URL
        - name: ENGINE_URI
          valueFrom:
            configMapKeyRef:
              key: engineUri
              name: odag-configs
        - name: ENGINE_URL
          value: $(ENGINE_URI)
        - $patch: delete
          name: NATS_URL
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: odag-configs
        - name: NATS_URL
          value: $(NATS_URI)
        - $patch: delete
          name: NATS_CLUSTER_ID
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: odag-configs
        - name: NATS_CLUSTER_ID
          value: $(NATS_STREAMING_CLUSTER_ID)
        - $patch: delete
          name: QIX_SESSION_URL
        - name: QIX_SESSIONS_URI
          valueFrom:
            configMapKeyRef:
              key: qixSessionsUri
              name: odag-configs
        - name: QIX_SESSION_URL
          value: $(QIX_SESSIONS_URI)
        - $patch: delete
          name: RELOAD_SERVICE_URL
        - name: RELOAD_SERVICE_URI
          valueFrom:
            configMapKeyRef:
              key: reloadServiceUri
              name: odag-configs
        - name: RELOAD_SERVICE_URL
          value: $(RELOAD_SERVICE_URI)
        - $patch: delete
          name: USER_SERVICE_URL
        - name: USERS_URI
          valueFrom:
            configMapKeyRef:
              key: usersUri
              name: odag-configs
        - name: USER_SERVICE_URL
          value: $(USERS_URI)
        - $patch: delete
          name: COLLECTIONS_URL
        - name: COLLECTIONS_URI
          valueFrom:
            configMapKeyRef:
              key: collectionsUri
              name: odag-configs
        - name: COLLECTIONS_URL
          value: $(COLLECTIONS_URI)
        - $patch: delete
          name: FEATURE_FLAG_URL
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: odag-configs
        - name: FEATURE_FLAG_URL
          value: $(FEATURE_FLAGS_URI)
        - $patch: delete
          name: ENCRYPTION_URL
        - name: ENCRYPTION_URI
          valueFrom:
            configMapKeyRef:
              key: encryptionUri
              name: odag-configs
        - name: ENCRYPTION_URL
          value: $(ENCRYPTION_URI)
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)
