apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../secrets
transformers:
  - ../../../../../.operator/keys/secrets/tenants
  - ../../../../../.operator/secrets
  - ../../../../../configuration/secrets
patches:
- target:
    kind: SuperSecret
  patch: |-
    - op: replace
      path: /metadata/name
      value: tenants-secrets