apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../secrets
transformers:
###
#  Temporary pre processing of Super* prefix until moved to configs/secrets folder at base
# for all components
  #- ../../../vars/prefix
###
  - ../../../../../.operator/keys/secrets/audit
  - ../../../../../.operator/secrets
  - ../../../../../configuration/secrets
patches:
  - target:
      kind: SuperSecret
    patch: |-
      - op: replace
        path: /metadata/name
        value: audit-secrets