apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: audit
enabled: true
patches:
  - path: deploymentJSON.yaml
    target:
      kind: Deployment
      name: audit
  - path: deployment.yaml
