apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: precedents
resources:
  - ../../../transformers
transformers:
- ../../../../../.operator/transformers
- ../../../../../configuration/transformers
#Disable all transformers except these
patches:
- target:
    labelSelector: >-
      key notin ( 
        featureFlagsUri,
        ingressClass,
        natsUri,
        natsStreamingClusterId,
        keysUri,
        mongoDbUri,
        spacesUri
      )
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: true
- target:
    labelSelector: "key=tokenAuthUri,kind=Deployment"
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: true