apiVersion: apps/v1
kind: Deployment
metadata:
  name: licenses
spec:
  template:
    metadata:
      labels:
        licenses-nats-client: null
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - $patch: delete
          name: PDS_URI
        - name: PDS_URI
          valueFrom:
            configMapKeyRef:
              key: pdsUri
              name: licenses-configs
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: licenses-configs
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: licenses-configs
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: licenses-secrets
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: licenses-configs
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: licenses-configs
        - $patch: delete
          name: TOKEN_AUTH_PRIVATE_KEY
        - name: TOKEN_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKey
              name: licenses-secrets
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: licenses-secrets
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: licenses-configs
        - $patch: delete
          name: TOKEN_AUTH_KID
        - name: TOKEN_AUTH_KID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - $patch: delete
          name: TOKEN_AUTH_URL
        - name: TOKEN_AUTH_URL
          value: $(TOKEN_AUTH_URI)/v1/internal-tokens
        - $patch: delete
          name: NATS_CLUSTER
        - name: NATS_CLUSTER
          value: $(NATS_STREAMING_CLUSTER_ID)
        - $patch: delete
          name: NATS_SERVERS
        - name: NATS_SERVERS
          value: $(NATS_URI)
        - $patch: delete
          name: LICENSES_MONGODB_URI
        - name: LICENSES_MONGODB_URI
          value: $(MONGODB_URI)
        - $patch: delete
          name: LICENSES_FEATURES_URI
        - name: LICENSES_FEATURES_URI
          value: $(FEATURE_FLAGS_URI)/v1/features
        - $patch: delete
          name: JWKS_ENDPOINT
        - name: JWKS_ENDPOINT
          value: $(KEYS_URI)/keys/qlik.api.internal
        # deleting TENANT_ID due to it getting a 'null' value
        - $patch: delete
          name: TENANT_ID
        # deleting TENANT_ID due to it getting a 'null' value
        - $patch: delete
          name: LICENSES_LOG_LEVEL
        - name: LICENSES_LOG_LEVEL
          value: info
        # not sure why NATS_CONNECT_ATTEMPTS get 0 while running in porter. so add this here
        - name: NATS_CONNECT_ATTEMPTS
          value: "3"
