apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: licenses
enabled: true
patches:
  - path: deploymentJSON.yaml
    target:
      kind: Deployment
      name: licenses
  - path: deployment.yaml
    target:
      kind: Deployment
      name: licenses
 
