apiVersion: apps/v1
kind: Deployment
metadata:
  name: reload-tasks
spec:
  template:
    metadata:
      labels:
        reload-tasks-nats-client: null
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - $patch: delete
          name: AUTH_JWKS_URI
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: reload-tasks-configs
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal
        - $patch: delete
          name: CHRONOS_URI
        - name: CHRONOS_URI
          valueFrom:
            configMapKeyRef:
              key: chronosUri
              name: reload-tasks-configs
        - $patch: delete
          name: CHRONOS_ACTION_URI
        - name: RELOADS_URI
          valueFrom:
            configMapKeyRef:
              key: reloadsUri
              name: reload-tasks-configs
        - name: CHRONOS_ACTION_URI
          value: $(RELOADS_URI)/v1/scheduledreloads
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: reload-tasks-secrets
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)