apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: qix-datafiles
resources:
  - ../../../../../generators/qix-datafiles
  - ../../../secrets
  - ../../../configs
transformers:
  - ../secrets
  - ../configs
  - values.yaml
patches:
  - target:
      kind: SuperSecret
    patch: |-
      - op: replace
        path: /metadata/name
        value: qix-datafiles-secrets
  - target:
      kind: SuperConfigMap
    patch: |-
      - op: replace
        path: /metadata/name
        value: qix-datafiles-configs
