apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-security
spec:
  template:
    spec:
      containers:
      - name: main
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongodbUri
              name: web-security-secrets
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: web-security-configs
        - $patch: delete
          name: JWKS_ENDPOINT
        - name: JWKS_ENDPOINT
          value: $(KEYS_URI)/keys/qlik.api.internal
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: web-security-configs
        - $patch: delete
          name: NATS_CLUSTER_ID
        - name: NATS_CLUSTER_ID
          value: $(NATS_STREAMING_CLUSTER_ID)
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: web-security-configs
        - $patch: delete
          name: NATS_URL
        - name: NATS_URL
          value: $(NATS_URI)
        - name: TOKEN_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKey
              name: web-security-secrets
        - $patch: delete
          name: PRIVATE_KEY
        - name: PRIVATE_KEY
          value: $(TOKEN_AUTH_PRIVATE_KEY)
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: web-security-secrets
        - $patch: delete
          name: KEY_ID
        - name: KEY_ID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: web-security-configs
        - $patch: delete
          name: INTERNAL_TOKENS_RESOURCE
        - name: INTERNAL_TOKENS_RESOURCE
          value: $(TOKEN_AUTH_URI)
        - name: TEMPORARY_CONTENTS_URI
          valueFrom:
            configMapKeyRef:
              key: temporaryContentsUri
              name: web-security-configs
        - $patch: delete
          name: TEMPORARY_CONTENTS_RESOURCE
        - name: TEMPORARY_CONTENTS_RESOURCE
          value: $(TEMPORARY_CONTENTS_URI)
        - name: ENCRYPTION_URI
          valueFrom:
            configMapKeyRef:
              key: encryptionUri
              name: web-security-configs
        - $patch: delete
          name: E2S_ADDR
        - name: E2S_ADDR
          value: $(TEMPORARY_CONTENTS_URI)
