apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../configs
transformers:
  - selectivepatch.yaml
  - ../../../../../.operator/configs
  - ../../../../../configuration/configs
patches:
  - target:
      kind: SuperConfigMap
    patch: |-
      - op: replace
        path: /metadata/name
        value: tenants-configs