apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: nl-broker-component-configs
enabled: true
patches:
- target:
    kind: SuperConfigMap
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    metadata:
      name: nl-broker-configs
    data:
      nlParserUri: "http://$(PREFIX)-nl-parser:30302"
      dataPrepUri: "http://$(PREFIX)-nl-broker-data-prep.svc.cluster.local:9072"
      keysUri: "http://$(PREFIX)-nl-broker-keys:8080/v1/keys/qlik.api.internal"


