apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clientCertificates
- corsUri
- encryptionUri
- featureFlagsUri
- groupsUri
- identityProvidersUri
- identityProvidersV1Uri
- idpConfigs
- ingressAuthUrl
- ingressClass
- keysUri
- mongoDbUri
- natsStreamingClusterId
- natsUri
- pdsUri
- redisPassword
- redisUri
- tenantsUri
- spacesUri
- tokenAuthUri
- usersUri
- qixSessionsUri
- dataFilesUri
- qixDataFilesUri
- precedentsUri
- licensesUri
- quotasUri
- temporaryContentsUri
- acceptEULA
- engineUri
- redisUriWithPort
- dcaasUri
- qixDataConnectionUri
- geoOperationsUri
- storageClassName
- reloadTasksUri
- qixDataReloadUri
- chronosUri
- reportingUri
- collectionsUri
- parserUri
- dpsUri
- insightsUri
- natsHttpUri
- keysUriTemp
- tokenAuthUriTemp
- licensesUriTemp
- caCertificates
