apiVersion: apps/v1
kind: Deployment
metadata:
  name: nl-broker
spec:
  template:
    metadata:
      labels:
        nl-broker-nats-client: null
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: nl-broker-secrets
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: nl-broker-configs
        - $patch: delete
          name: AUTH_JWKS_URI
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: nl-broker-configs
        - name: EDGE_AUTH_URL
          value: $(TOKEN_AUTH_URI)
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)
        - $patch: delete
          name: DPS_URI
        - name: DPS_URI
          valueFrom:
            configMapKeyRef:
              key: dpsUri
              name: nl-broker-configs
        - name: DPS_URI
          value: $(DPS_URI)
        - $patch: delete
          name: PARSER_URI
        - name: PARSER_URI
          valueFrom:
            configMapKeyRef:
              key: parserUri
              name: nl-broker-configs
        - name: PARSER_URI
          value: $(PARSER_URI)
