apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenants
spec:
  template:
    metadata:
      labels:
        tenants-nats-client: null
    spec:
      volumes:
      - name: tenants-secret
        secret:
          secretName: tenants-secrets
          items:
            - key: tokenAuthPrivateKey
              path: jwtPrivateKey
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - $patch: delete
          name: NATS_URL
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: tenants-configs
        - name: NATS_URL
          value: $(NATS_URI)
        - $patch: delete
          name: NATS_CLUSTER_ID
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: tenants-configs
        - name: NATS_CLUSTER_ID
          value: $(NATS_STREAMING_CLUSTER_ID)
        - $patch: delete
          name: MONGO_URI
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: tenants-secrets
        - name: MONGO_URI
          value: $(MONGODB_URI)
        #  JWKS_ENDPOINT -> KEYS_URI
        - $patch: delete
          name: JWKS_ENDPOINT
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: tenants-configs
        - name: JWKS_ENDPOINT
          value: $(KEYS_URI)/keys/qlik.api.internal
        # USERS_RESOURCE -> USERS_URI
        - $patch: delete
          name: USERS_RESOURCE
        - name: USERS_URI
          valueFrom:
            configMapKeyRef:
              key: usersUri
              name: tenants-configs
        - name: USERS_RESOURCE
          value: $(USERS_URI)
        # LICENSES_RESOURCE -> LICENSES_URI
        - $patch: delete
          name: LICENSES_RESOURCE
        - name: LICENSES_URI
          valueFrom:
            configMapKeyRef:
              key: licensesUri
              name: tenants-configs
        - name: LICENSES_RESOURCE
          value: $(LICENSES_URI)/v1
        # FEATURE_FLAGS_RESOURCE -> FEATURE_FLAGS_URI
        - $patch: delete
          name: FEATURE_FLAGS_RESOURCE
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: tenants-configs
        - name: FEATURE_FLAGS_RESOURCE
          value: $(FEATURE_FLAGS_URI)
        # INTERNAL_TOKENS_RESOURCE -> TOKEN_AUTH_URI
        - $patch: delete
          name: INTERNAL_TOKENS_RESOURCE
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: tenants-configs
        - name: INTERNAL_TOKENS_RESOURCE
          value: $(TOKEN_AUTH_URI)/v1
        - $patch: delete
          name: KEY_ID
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: tenants-secrets
        - name: KEY_ID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
