apiVersion: qlik.com/v1
kind: HelmValues
metadata:
  name: redis 
releaseNamespace: $(NAMESPACE)
values:
  usePassword: true
  existingSecret: "redis-secrets"
  cluster:
    enabled: true
  master:
    securityContext:
      enabled: false
