apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: cert-manager
generators:
  - generators
resources:
  - resources
# images:
#   - name: quay.io/external_storage/nfs-client-provisioner
#     newName: $(IMAGE_REGISTRY)/nfs-client-provisioner
