apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  template:
    metadata:
      labels:
        users-nats-client: null
    spec:
      volumes:
      - name: users-secret
        secret:
          secretName: users-secrets
          items:
            - key: tokenAuthPrivateKey
              path: jwtPrivateKey
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: users-configs
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: users-configs
        - $patch: delete
          name: FEATURE_FLAGS_RESOURCE
        - name: FEATURE_FLAGS_RESOURCE
          value: $(FEATURE_FLAGS_URI)/v1
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: users-secrets
        - $patch: delete
          name: JWKS_ENDPOINT
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: users-configs
        - name: JWKS_ENDPOINT
          value: $(KEYS_URI)/keys/qlik.api.internal
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: users-configs
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: users-configs
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: users-secrets
        - $patch: delete
          name: KEY_ID
        - name: KEY_ID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)
        - $patch: delete
          name: NATS_URL
        - name: NATS_URL
          value: $(NATS_URI)
        - $patch: delete
          name: NATS_CLUSTER_ID
        - name: NATS_CLUSTER_ID
          value: $(NATS_STREAMING_CLUSTER_ID)
        # deleting ACCOUNT due to it getting a 'null' value
        - $patch: delete
          name: ACCOUNT
        - name: INTERNAL_TOKENS_RESOURCE
          value: $(TOKEN_AUTH_URI)/v1
