apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: messaging-nats-streaming
spec:
  serviceName: ""
  template:
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        args:
        - -cid
        - $(NATS_STREAMING_CLUSTER_ID)
        - -m
        - "8222"
        - -ns
        - $(NATS_URI)
        - -mc
        - "100"
        - -msu
        - "1000"
        - -mm
        - "1000000"
        - -mb
        - 900mb
        - -ma
        - 2h
        - -hbi
        - 10s
        - -hbt
        - 10s
        - -hbf
        - "5"
        - -clustered
        - --cluster_node_id
        - $(POD_NAME)
        - --cluster_peers
        - $(PREFIX)-messaging-nats-streaming-0,$(PREFIX)-messaging-nats-streaming-1,$(PREFIX)-messaging-nats-streaming-2
        - --cluster_log_path
        - /nats/$(PREFIX)-messaging-nats-streaming-cluster/$(POD_NAME)/raft
        - --store
        - file
        - --dir
        - /nats/$(PREFIX)-messaging-nats-streaming-cluster/$(POD_NAME)/data
        - --file_compact_enabled
        - --file_compact_frag
        - "50"
        - --file_compact_interval
        - "300"
        - --file_compact_min_size
        - "1048576"
        - --file_buffer_size
        - "2097152"
        - --file_crc
        - --file_crc_poly
        - "3988292384"
        - --file_sync
        - --file_slice_max_msgs
        - "0"
        - --file_slice_max_bytes
        - "67108931"
        - --file_slice_max_age
        - "0"
        - --file_fds_limit
        - "0"
        - --file_parallel_recovery
        - "1"
        - --user
        - $(USER)
        - --pass
        - $(PASSWORD)
        - -SD
        env:
        # - name: ACCEPT_EULA
        #   valueFrom:
        #     configMapKeyRef:
        #       key: acceptEULA
        #       name: engine-configs
        # - name: KEYS_URI
        #   valueFrom:
        #     configMapKeyRef:
        #       key: keysUri
        #       name: engine-configs
        # - name: TOKEN_AUTH_PRIVATE_KEY_ID
        #   valueFrom:
        #     secretKeyRef:
        #       key: tokenAuthPrivateKeyId
        #       name: engine-secrets
        # - name: TOKEN_AUTH_URI
        #   valueFrom:
        #     configMapKeyRef:
        #       key: tokenAuthUri 
        #       name: engine-configs
        # - name: LICENSES_URI
        #   valueFrom:
        #     configMapKeyRef:
        #       key: licensesUri 
        #       name: engine-configs
        # - name: SPACES_URI
        #   valueFrom:
        #     configMapKeyRef:
        #       key: spacesUri 
        #       name: engine-configs
        # - name: FEATURE_FLAGS_URI
        #   valueFrom:
        #     configMapKeyRef:
        #       key: featureFlagsUri
        #       name: engine-configs
        # - name: GROUPS_URI
        #   valueFrom:
        #     configMapKeyRef:
        #       key: groupsUri
        #       name: engine-configs
        # - name: TEMPORARY_CONTENTS_URI
        #   valueFrom:
        #     configMapKeyRef:
        #       key: temporaryContentsUri
        #       name: engine-configs
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: messaging-configs
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: messaging-configs
